# Generated by Django 4.2.11 on 2024-03-20 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000, verbose_name='Assunto')),
                ('category', models.CharField(max_length=500, verbose_name='Categoria')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Postagem')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Imagem')),
                ('message', models.TextField(max_length=15000, verbose_name='Mensagem')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
